apiVersion: 1
datasources:
  - name: FlintGraph metrics
    uid: flint-graph-metrics
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
